# <b>Driving Risk Prediction System</b>
## Name: Muhammad jahanzaib
## RollNumber: SU92-BSAIM-S25-047

<div class="alert alert-block alert-warning">
    Dataset: <b>Driver Behavior &amp; Route Anomaly Dataset with Derived Features</b><br>
    120,000 records — Vehicle sensors, GPS, route &amp; behavioural signals
</div>

<div class="alert alert-block alert-danger">
    <b>Problem Statement</b><br>
    Predict the <b>Driving Risk Level</b> of a trip as <b>Low</b>, <b>Medium</b>, or <b>High</b>
    based on driver behaviour, vehicle sensor data, route anomalies and environmental conditions.
</div>

<div class="alert alert-block alert-info">
    <b>Machine Learning Steps</b><br>
    1. Data Reading / Data Loading<br>
    2. Data Exploration<br>
    3. Data Pre-Processing<br>
    4. Train-Test Splitting<br>
    5. Model Application (Random Forest)<br>
    6. Model Accuracy<br>
    7. Application Phase
</div>

# Libraries

In [1]:
!pip install pandas numpy scikit-learn joblib --quiet

In [2]:
import pandas as pd
import numpy as np
import joblib, pickle, warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble         import RandomForestClassifier
from sklearn.metrics          import accuracy_score
from sklearn.preprocessing    import LabelEncoder
from sklearn.model_selection  import train_test_split

print("Libraries imported successfully!")

Libraries imported successfully!

<div class="alert alert-block alert-success">
    <h1>1. Data Reading / Data Loading</h1>
</div>

#### File: `driver_behavior_route_anomaly_dataset_with_derived_features.csv`

In [4]:
data = pd.read_csv('driver_behavior_route_anomaly_dataset_with_derived_features.csv')
print(f"Dataset loaded — {data.shape[0]:,} rows x {data.shape[1]} columns")
data

Dataset loaded — 120,000 rows x 26 columns

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.916143,-80.345269,39.484646,3.612832,6,212.555994,...,Sunny,Urban,Light,0,0,0,0,0.176974,0.715284,0.468189
1,2,105,2002,2023-01-01 00:00:01,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,...,Sunny,Highway,Light,0,0,1,0,0.229316,0.487761,0.234935
2,3,103,2002,2023-01-01 00:00:02,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,...,Cloudy,Urban,Moderate,0,0,0,0,0.473809,0.881141,0.192588
3,4,102,2002,2023-01-01 00:00:03,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,...,Sunny,Highway,Moderate,3,0,0,0,0.368063,0.937918,0.363707
4,5,101,2002,2023-01-01 00:00:04,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,...,Sunny,Rural,Moderate,0,0,0,0,0.145270,0.702187,0.178748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,119996,101,1001,2023-01-02 09:19:55,43.054036,-86.197119,10.263763,-0.802541,18,53.521771,...,Sunny,Urban,Moderate,0,0,0,0,0.232350,0.375641,0.067177
119996,119997,101,2002,2023-01-02 09:19:56,35.551541,-73.439461,40.431564,-0.532927,18,86.945711,...,Foggy,Urban,Moderate,1,1,1,0,0.431830,0.822901,0.096263
119997,119998,101,1001,2023-01-02 09:19:57,41.964624,-95.333223,53.893048,0.734331,7,288.027901,...,Rainy,Highway,Moderate,2,0,0,0,0.089747,0.817555,0.171400
119998,119999,101,2002,2023-01-02 09:19:58,30.356801,-79.892936,65.559146,0.366847,-11,249.409519,...,Cloudy,Urban,Light,1,0,0,0,0.614545,0.798756,0.452616
119999,120000,101,1001,2023-01-02 09:19:59,32.707254,-92.526916,10.351467,-0.321536,2,71.344715,...,Cloudy,Urban,Moderate,2,0,0,0,0.150682,0.753897,0.393896

<div class="alert alert-block alert-success">
    <h1>2. Data Exploration</h1>
</div>

In [5]:
data.head()

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.916143,-80.345269,39.484646,3.612832,6,212.555994,...,Sunny,Urban,Light,0,0,0,0,0.176974,0.715284,0.468189
1,2,105,2002,2023-01-01 00:00:01,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,...,Sunny,Highway,Light,0,0,1,0,0.229316,0.487761,0.234935
2,3,103,2002,2023-01-01 00:00:02,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,...,Cloudy,Urban,Moderate,0,0,0,0,0.473809,0.881141,0.192588
3,4,102,2002,2023-01-01 00:00:03,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,...,Sunny,Highway,Moderate,3,0,0,0,0.368063,0.937918,0.363707
4,5,101,2002,2023-01-01 00:00:04,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,...,Sunny,Rural,Moderate,0,0,0,0,0.145270,0.702187,0.178748

In [6]:
data.tail()

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
119995,119996,101,1001,2023-01-02 09:19:55,43.054036,-86.197119,10.263763,-0.802541,18,53.521771,...,Sunny,Urban,Moderate,0,0,0,0,0.232350,0.375641,0.067177
119996,119997,101,2002,2023-01-02 09:19:56,35.551541,-73.439461,40.431564,-0.532927,18,86.945711,...,Foggy,Urban,Moderate,1,1,1,0,0.431830,0.822901,0.096263
119997,119998,101,1001,2023-01-02 09:19:57,41.964624,-95.333223,53.893048,0.734331,7,288.027901,...,Rainy,Highway,Moderate,2,0,0,0,0.089747,0.817555,0.171400
119998,119999,101,2002,2023-01-02 09:19:58,30.356801,-79.892936,65.559146,0.366847,-11,249.409519,...,Cloudy,Urban,Light,1,0,0,0,0.614545,0.798756,0.452616
119999,120000,101,1001,2023-01-02 09:19:59,32.707254,-92.526916,10.351467,-0.321536,2,71.344715,...,Cloudy,Urban,Moderate,2,0,0,0,0.150682,0.753897,0.393896

In [7]:
data.shape

(120000, 26)

In [8]:
data.columns

Index(['trip_id', 'driver_id', 'vehicle_id', 'timestamp', 'latitude',
       'longitude', 'speed', 'acceleration', 'steering_angle', 'heading',
       'trip_duration', 'trip_distance', 'fuel_consumption', 'rpm',
       'brake_usage', 'lane_deviation', 'weather_conditions', 'road_type',
       'traffic_condition', 'stop_events', 'geofencing_violation',
       'anomalous_event', 'route_anomaly', 'route_deviation_score',
       'acceleration_variation', 'behavioral_consistency_index'],
      dtype='object')

In [9]:
data.count()

trip_id                         120000
driver_id                       120000
vehicle_id                      120000
timestamp                       120000
latitude                        120000
longitude                       120000
speed                           120000
acceleration                    120000
steering_angle                  120000
heading                         120000
trip_duration                   120000
trip_distance                   120000
fuel_consumption                120000
rpm                             120000
brake_usage                     120000
lane_deviation                  120000
weather_conditions              120000
road_type                       120000
traffic_condition               120000
stop_events                     120000
geofencing_violation            120000
anomalous_event                 120000
route_anomaly                   120000
route_deviation_score           120000
acceleration_variation          120000
behavioral_consistency_index    120000
dtype: int64

In [10]:
data.nunique()

trip_id                         120000
driver_id                            5
vehicle_id                           5
timestamp                       120000
latitude                        120000
longitude                       120000
speed                           120000
acceleration                    120000
steering_angle                      91
heading                         120000
trip_duration                   120000
trip_distance                   120000
fuel_consumption                120000
rpm                             120000
brake_usage                         19
lane_deviation                  120000
weather_conditions                   4
road_type                            3
traffic_condition                    3
stop_events                          9
geofencing_violation                 2
anomalous_event                      2
route_anomaly                        2
route_deviation_score           120000
acceleration_variation          120000
behavioral_consistency_index    120000
dtype: int64

In [11]:
print('weather_conditions :', data['weather_conditions'].unique())
print('road_type          :', data['road_type'].unique())
print('traffic_condition  :', data['traffic_condition'].unique())

weather_conditions : ['Sunny' 'Cloudy' 'Foggy' 'Rainy']
road_type          : ['Urban' 'Highway' 'Rural']
traffic_condition  : ['Light' 'Moderate' 'Heavy']

In [12]:
data.describe()

,trip_id,driver_id,vehicle_id,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,...,rpm,brake_usage,lane_deviation,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
count,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,...,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000
mean,60000.500000,102.098875,2106.479375,39.990066,-90.002296,29.971987,1.003904,0.082442,179.923038,3593.505077,...,1991.533620,4.995767,0.285753,0.996800,0.050242,0.100167,0.099708,0.285187,0.714811,0.285855
std,34641.160489,1.371367,1379.539988,5.002472,10.026103,30.211853,1.998322,14.870230,103.833915,3595.552160,...,1498.933743,2.240727,0.159819,1.001481,0.218444,0.300223,0.299612,0.159840,0.159045,0.160088
min,1.000000,101.000000,1001.000000,17.930570,-133.129729,0.000157,-0.999910,-45.000000,0.000915,0.001821,...,500.015651,0.000000,0.000354,0.000000,0.000000,0.000000,0.000000,0.000305,0.075593,0.000295
25%,30000.750000,101.000000,1001.000000,36.623453,-96.799608,8.615250,-0.419030,-10.000000,89.972635,1032.752956,...,927.900033,3.000000,0.161382,0.000000,0.000000,0.000000,0.000000,0.160065,0.611532,0.160986
50%,60000.500000,102.000000,2002.000000,39.987503,-89.969652,20.633107,0.388639,0.000000,179.859502,2484.164733,...,1535.258915,5.000000,0.264586,1.000000,0.000000,0.000000,0.000000,0.263214,0.735854,0.264427
75%,90000.250000,103.000000,3003.000000,43.357958,-83.241541,41.439832,1.777851,10.000000,269.673973,4975.872175,...,2563.837376,6.000000,0.389144,2.000000,0.000000,0.000000,0.000000,0.389066,0.838992,0.389694
max,120000.000000,105.000000,5005.000000,61.096832,-46.981523,365.764111,22.032532,45.000000,359.996851,46866.782872,...,18879.432692,19.000000,0.932762,8.000000,1.000000,1.000000,1.000000,0.948786,0.999540,0.942612

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 26 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   trip_id                       120000 non-null  int64
 1   driver_id                     120000 non-null  int64
 2   vehicle_id                    120000 non-null  int64
 3   timestamp                     120000 non-null  object
 4   latitude                      120000 non-null  float64
 5   longitude                     120000 non-null  float64
 6   speed                         120000 non-null  float64
 7   acceleration                  120000 non-null  float64
 8   steering_angle                120000 non-null  int64
 9   heading                       120000 non-null  float64
 10  trip_duration                 120000 non-null  float64
 11  trip_distance                 120000 non-null  float64
 12  fuel_consumption              120000 non-null  float64
 13  rpm                           120000 non-null  float64
 14  brake_usage                   120000 non-null  int64
 15  lane_deviation                120000 non-null  float64
 16  weather_conditions            120000 non-null  object
 17  road_type                     120000 non-null  object
 18  traffic_condition             120000 non-null  object
 19  stop_events                   120000 non-null  int64
 20  geofencing_violation          120000 non-null  int64
 21  anomalous_event               120000 non-null  int64
 22  route_anomaly                 120000 non-null  int64
 23  route_deviation_score         120000 non-null  float64
 24  acceleration_variation        120000 non-null  float64
 25  behavioral_consistency_index  120000 non-null  float64
dtypes: float64(13), int64(9), object(4)
memory usage: 23.8+ MB

In [14]:
data.isnull().sum()

trip_id                         0
driver_id                       0
vehicle_id                      0
timestamp                       0
latitude                        0
longitude                       0
speed                           0
acceleration                    0
steering_angle                  0
heading                         0
trip_duration                   0
trip_distance                   0
fuel_consumption                0
rpm                             0
brake_usage                     0
lane_deviation                  0
weather_conditions              0
road_type                       0
traffic_condition               0
stop_events                     0
geofencing_violation            0
anomalous_event                 0
route_anomaly                   0
route_deviation_score           0
acceleration_variation          0
behavioral_consistency_index    0
dtype: int64

<div class="alert alert-block alert-success">
    <h1>3. Data Pre-Processing</h1>
</div>

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 26 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   trip_id                       120000 non-null  int64
 1   driver_id                     120000 non-null  int64
 2   vehicle_id                    120000 non-null  int64
 3   timestamp                     120000 non-null  object
 4   latitude                      120000 non-null  float64
 5   longitude                     120000 non-null  float64
 6   speed                         120000 non-null  float64
 7   acceleration                  120000 non-null  float64
 8   steering_angle                120000 non-null  int64
 9   heading                       120000 non-null  float64
 10  trip_duration                 120000 non-null  float64
 11  trip_distance                 120000 non-null  float64
 12  fuel_consumption              120000 non-null  float64
 13  rpm                           120000 non-null  float64
 14  brake_usage                   120000 non-null  int64
 15  lane_deviation                120000 non-null  float64
 16  weather_conditions            120000 non-null  object
 17  road_type                     120000 non-null  object
 18  traffic_condition             120000 non-null  object
 19  stop_events                   120000 non-null  int64
 20  geofencing_violation          120000 non-null  int64
 21  anomalous_event               120000 non-null  int64
 22  route_anomaly                 120000 non-null  int64
 23  route_deviation_score         120000 non-null  float64
 24  acceleration_variation        120000 non-null  float64
 25  behavioral_consistency_index  120000 non-null  float64
dtypes: float64(13), int64(9), object(4)
memory usage: 23.8+ MB

In [16]:
data.isnull().sum()

trip_id                         0
driver_id                       0
vehicle_id                      0
timestamp                       0
latitude                        0
longitude                       0
speed                           0
acceleration                    0
steering_angle                  0
heading                         0
trip_duration                   0
trip_distance                   0
fuel_consumption                0
rpm                             0
brake_usage                     0
lane_deviation                  0
weather_conditions              0
road_type                       0
traffic_condition               0
stop_events                     0
geofencing_violation            0
anomalous_event                 0
route_anomaly                   0
route_deviation_score           0
acceleration_variation          0
behavioral_consistency_index    0
dtype: int64

In [17]:
data.shape

(120000, 26)

In [18]:
data.drop('trip_id',    axis=1, inplace=True)
data.drop('driver_id',  axis=1, inplace=True)
data.drop('vehicle_id', axis=1, inplace=True)
print("ID columns dropped. Remaining:", data.shape[1], "columns")

ID columns dropped. Remaining: 23 columns

In [19]:
data['timestamp']   = pd.to_datetime(data['timestamp'])
data['hour']        = data['timestamp'].dt.hour
data['day_of_week'] = data['timestamp'].dt.dayofweek
data['is_weekend']  = (data['day_of_week'] >= 5).astype(int)
data['is_night']    = ((data['hour'] >= 22) | (data['hour'] <= 5)).astype(int)
data.drop('timestamp', axis=1, inplace=True)
print("Timestamp parsed. New features: hour, day_of_week, is_weekend, is_night")

Timestamp parsed. New features: hour, day_of_week, is_weekend, is_night

In [20]:
data.head()

,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,trip_distance,fuel_consumption,rpm,...,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index,hour,day_of_week,is_weekend,is_night
0,38.916143,-80.345269,39.484646,3.612832,6,212.555994,250.980424,24.868334,19.293594,8300.855056,...,0,0,0,0.176974,0.715284,0.468189,0,6,1,1
1,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,2112.678280,10.230086,2.011132,2290.934075,...,0,1,0,0.229316,0.487761,0.234935,0,6,1,1
2,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,1134.936064,23.483279,4.025824,1299.930836,...,0,0,0,0.473809,0.881141,0.192588,0,6,1,1
3,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,11651.719966,1.480827,1.233628,3825.966601,...,0,0,0,0.368063,0.937918,0.363707,0,6,1,1
4,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,1033.826911,131.294800,2.720884,2376.000694,...,0,0,0,0.145270,0.702187,0.178748,0,6,1,1

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 26 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   latitude                      120000 non-null  float64
 1   longitude                     120000 non-null  float64
 2   speed                         120000 non-null  float64
 3   acceleration                  120000 non-null  float64
 4   steering_angle                120000 non-null  int64
 5   heading                       120000 non-null  float64
 6   trip_duration                 120000 non-null  float64
 7   trip_distance                 120000 non-null  float64
 8   fuel_consumption              120000 non-null  float64
 9   rpm                           120000 non-null  float64
 10  brake_usage                   120000 non-null  int64
 11  lane_deviation                120000 non-null  float64
 12  weather_conditions            120000 non-null  object
 13  road_type                     120000 non-null  object
 14  traffic_condition             120000 non-null  object
 15  stop_events                   120000 non-null  int64
 16  geofencing_violation          120000 non-null  int64
 17  anomalous_event               120000 non-null  int64
 18  route_anomaly                 120000 non-null  int64
 19  route_deviation_score         120000 non-null  float64
 20  acceleration_variation        120000 non-null  float64
 21  behavioral_consistency_index  120000 non-null  float64
 22  hour                          120000 non-null  int32
 23  day_of_week                   120000 non-null  int32
 24  is_weekend                    120000 non-null  int64
 25  is_night                      120000 non-null  int64
dtypes: float64(13), int32(2), int64(8), object(3)
memory usage: 22.9+ MB

In [22]:
def fillnaMean(cols):
    for i in cols:
        data[i] = data[i].fillna(data[i].mean())

columns = ['speed','acceleration','heading','trip_duration','trip_distance',
           'fuel_consumption','rpm','lane_deviation','route_deviation_score',
           'acceleration_variation','behavioral_consistency_index',
           'latitude','longitude']
fillnaMean(columns)
print("Numerical columns filled with mean.")

Numerical columns filled with mean.

In [23]:
def fillnaMode(cols):
    for i in cols:
        data[i] = data[i].fillna(data[i].mode()[0])

columns = ['steering_angle','brake_usage','stop_events',
           'geofencing_violation','anomalous_event','route_anomaly',
           'weather_conditions','road_type','traffic_condition',
           'hour','day_of_week','is_weekend','is_night']
fillnaMode(columns)
print("Categorical/integer columns filled with mode.")

Categorical/integer columns filled with mode.

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 26 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   latitude                      120000 non-null  float64
 1   longitude                     120000 non-null  float64
 2   speed                         120000 non-null  float64
 3   acceleration                  120000 non-null  float64
 4   steering_angle                120000 non-null  int64
 5   heading                       120000 non-null  float64
 6   trip_duration                 120000 non-null  float64
 7   trip_distance                 120000 non-null  float64
 8   fuel_consumption              120000 non-null  float64
 9   rpm                           120000 non-null  float64
 10  brake_usage                   120000 non-null  int64
 11  lane_deviation                120000 non-null  float64
 12  weather_conditions            120000 non-null  object
 13  road_type                     120000 non-null  object
 14  traffic_condition             120000 non-null  object
 15  stop_events                   120000 non-null  int64
 16  geofencing_violation          120000 non-null  int64
 17  anomalous_event               120000 non-null  int64
 18  route_anomaly                 120000 non-null  int64
 19  route_deviation_score         120000 non-null  float64
 20  acceleration_variation        120000 non-null  float64
 21  behavioral_consistency_index  120000 non-null  float64
 22  hour                          120000 non-null  int32
 23  day_of_week                   120000 non-null  int32
 24  is_weekend                    120000 non-null  int64
 25  is_night                      120000 non-null  int64
dtypes: float64(13), int32(2), int64(8), object(3)
memory usage: 22.9+ MB

In [25]:
def cap_outliers_iqr(cols):
    for col in cols:
        Q1    = data[col].quantile(0.25)
        Q3    = data[col].quantile(0.75)
        IQR   = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        n_out = ((data[col] < lower) | (data[col] > upper)).sum()
        data[col] = data[col].clip(lower=lower, upper=upper)
        if n_out > 0:
            print(f"  '{col}': {n_out} outliers capped  [{lower:.2f}, {upper:.2f}]")

columns = ['speed','acceleration','rpm','fuel_consumption','trip_duration',
           'trip_distance','lane_deviation','route_deviation_score',
           'acceleration_variation','behavioral_consistency_index','brake_usage']
cap_outliers_iqr(columns)
print("Outlier capping complete.")

  'speed': 5945 outliers capped  [-40.62, 90.68]
  'acceleration': 5750 outliers capped  [-3.71, 5.07]
  'rpm': 5842 outliers capped  [-1526.01, 5017.74]
  'fuel_consumption': 5785 outliers capped  [-6.76, 15.12]
  'trip_duration': 5835 outliers capped  [-4881.93, 10890.55]
  'trip_distance': 5833 outliers capped  [-67.91, 151.37]
  'lane_deviation': 747 outliers capped  [-0.18, 0.73]
  'route_deviation_score': 731 outliers capped  [-0.18, 0.73]
  'acceleration_variation': 793 outliers capped  [0.27, 1.18]
  'behavioral_consistency_index': 770 outliers capped  [-0.18, 0.73]
  'brake_usage': 1677 outliers capped  [-1.50, 10.50]
Outlier capping complete.

In [26]:
def changetoInt64(cols):
    for i in cols:
        data[i] = data[i].astype('int64')

columns = ['steering_angle','brake_usage','stop_events','geofencing_violation',
           'anomalous_event','route_anomaly','hour','day_of_week','is_weekend','is_night']
changetoInt64(columns)
print("Integer type conversion done.")

Integer type conversion done.

## Creating the Categorical Target: `risk_level`

| Risk Level | Condition |
|---|---|
| **High** | `route_anomaly=1` OR `anomalous_event=1` OR `geofencing_violation=1` OR (very high speed AND low consistency) |
| **Medium** | Above-average speed OR high lane deviation OR high route/acceleration deviation |
| **Low** | Normal safe driving |

In [27]:
data['risk_level'] = 'Low'

medium_mask = (
    (data['speed']                  > data['speed'].quantile(0.75)) |
    (data['lane_deviation']         > data['lane_deviation'].quantile(0.75)) |
    (data['route_deviation_score']  > data['route_deviation_score'].quantile(0.75)) |
    (data['acceleration_variation'] > data['acceleration_variation'].quantile(0.75)) |
    (data['brake_usage']            > data['brake_usage'].quantile(0.75))
)
data.loc[medium_mask, 'risk_level'] = 'Medium'

high_mask = (
    (data['route_anomaly']        == 1) |
    (data['anomalous_event']      == 1) |
    (data['geofencing_violation'] == 1) |
    (
        (data['speed'] > data['speed'].quantile(0.90)) &
        (data['behavioral_consistency_index'] <
         data['behavioral_consistency_index'].quantile(0.10))
    )
)
data.loc[high_mask, 'risk_level'] = 'High'

print("risk_level distribution:")
print(data['risk_level'].value_counts())

risk_level distribution:
risk_level
Medium    68954
High      28650
Low       22396
Name: count, dtype: int64

In [28]:
data.drop('route_anomaly',        axis=1, inplace=True)
data.drop('anomalous_event',      axis=1, inplace=True)
data.drop('geofencing_violation', axis=1, inplace=True)
print("Leakage columns dropped. Columns remaining:", data.shape[1])

Leakage columns dropped. Columns remaining: 24

In [29]:
encoders = {}

def encodeCols(cols):
    for i in cols:
        value = pd.DataFrame({i: data[i].unique()})
        LE = LabelEncoder()
        LE.fit(value)
        data[i] = LE.transform(data[i])
        encoders[i] = LE
        print(f"  Encoded '{i}': {list(LE.classes_)}")

columns = ['weather_conditions','road_type','traffic_condition','risk_level']
encodeCols(columns)

joblib.dump(encoders, 'encoders.pkl')
print("\nEncoders saved to encoders.pkl")

  Encoded 'weather_conditions': ['Cloudy', 'Foggy', 'Rainy', 'Sunny']
  Encoded 'road_type': ['Highway', 'Rural', 'Urban']
  Encoded 'traffic_condition': ['Heavy', 'Light', 'Moderate']
  Encoded 'risk_level': ['High', 'Low', 'Medium']

Encoders saved to encoders.pkl

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120000 entries, 0 to 119999
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   latitude                      120000 non-null  float64
 1   longitude                     120000 non-null  float64
 2   speed                         120000 non-null  float64
 3   acceleration                  120000 non-null  float64
 4   steering_angle                120000 non-null  int64
 5   heading                       120000 non-null  float64
 6   trip_duration                 120000 non-null  float64
 7   trip_distance                 120000 non-null  float64
 8   fuel_consumption              120000 non-null  float64
 9   rpm                           120000 non-null  float64
 10  brake_usage                   120000 non-null  int64
 11  lane_deviation                120000 non-null  float64
 12  weather_conditions            120000 non-null  int64
 13  road_type                     120000 non-null  int64
 14  traffic_condition             120000 non-null  int64
 15  stop_events                   120000 non-null  int64
 16  route_deviation_score         120000 non-null  float64
 17  acceleration_variation        120000 non-null  float64
 18  behavioral_consistency_index  120000 non-null  float64
 19  hour                          120000 non-null  int64
 20  day_of_week                   120000 non-null  int64
 21  is_weekend                    120000 non-null  int64
 22  is_night                      120000 non-null  int64
 23  risk_level                    120000 non-null  int64
dtypes: float64(13), int64(11)
memory usage: 22.0 MB

In [31]:
data.to_csv('cleaned_data.csv', index=False, header=True)
print('Cleaned data saved to cleaned_data.csv')

Cleaned data saved to cleaned_data.csv

<div class="alert alert-block alert-success">
    <h1>4. Train-Test Splitting</h1>
</div>

In [32]:
data = pd.read_csv('cleaned_data.csv')

In [33]:
data.head()

,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,trip_distance,fuel_consumption,rpm,...,traffic_condition,stop_events,route_deviation_score,acceleration_variation,behavioral_consistency_index,hour,day_of_week,is_weekend,is_night,risk_level
0,38.916143,-80.345269,39.484646,3.612832,6,212.555994,250.980424,24.868334,15.116212,5017.743391,...,1,0,0.176974,0.715284,0.468189,0,6,1,1,1
1,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,2112.678280,10.230086,2.011132,2290.934075,...,1,0,0.229316,0.487761,0.234935,0,6,1,1,0
2,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,1134.936064,23.483279,4.025824,1299.930836,...,2,0,0.473809,0.881141,0.192588,0,6,1,1,2
3,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,10890.551002,1.480827,1.233628,3825.966601,...,2,3,0.368063,0.937918,0.363707,0,6,1,1,2
4,30.473386,-92.362577,13.061111,5.073173,-1,333.804023,1033.826911,131.294800,2.720884,2376.000694,...,2,0,0.145270,0.702187,0.178748,0,6,1,1,1

In [34]:
data.columns

Index(['latitude', 'longitude', 'speed', 'acceleration', 'steering_angle',
       'heading', 'trip_duration', 'trip_distance', 'fuel_consumption', 'rpm',
       'brake_usage', 'lane_deviation', 'weather_conditions', 'road_type',
       'traffic_condition', 'stop_events', 'route_deviation_score',
       'acceleration_variation', 'behavioral_consistency_index', 'hour',
       'day_of_week', 'is_weekend', 'is_night', 'risk_level'],
      dtype='object')

In [35]:
X = data.drop('risk_level', axis=1)
y = data['risk_level']

In [36]:
X.head()

,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,trip_distance,fuel_consumption,rpm,...,road_type,traffic_condition,stop_events,route_deviation_score,acceleration_variation,behavioral_consistency_index,hour,day_of_week,is_weekend,is_night
0,38.916143,-80.345269,39.484646,3.612832,6,212.555994,250.980424,24.868334,15.116212,5017.743391,...,2,1,0,0.176974,0.715284,0.468189,0,6,1,1
1,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,2112.678280,10.230086,2.011132,2290.934075,...,0,1,0,0.229316,0.487761,0.234935,0,6,1,1
2,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,1134.936064,23.483279,4.025824,1299.930836,...,2,2,0,0.473809,0.881141,0.192588,0,6,1,1
3,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,10890.551002,1.480827,1.233628,3825.966601,...,0,2,3,0.368063,0.937918,0.363707,0,6,1,1
4,30.473386,-92.362577,13.061111,5.073173,-1,333.804023,1033.826911,131.294800,2.720884,2376.000694,...,1,2,0,0.145270,0.702187,0.178748,0,6,1,1

In [37]:
y.head()

0    1
1    0
2    2
3    2
4    1
Name: risk_level, dtype: int64

In [38]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.2, shuffle=False)

In [39]:
# train_X.head()
# train_y.head()

In [40]:
# test_X.head()
# test_y.head()

In [41]:
print("train_X:", train_X.shape, " train_y:", train_y.shape)
print("test_X :", test_X.shape,  " test_y :", test_y.shape)

train_X: (96000, 23)  train_y: (96000,)
test_X : (24000, 23)  test_y : (24000,)

<div class="alert alert-block alert-success">
    <h1>5. Model Application</h1>
</div>

## Training Model using Classification : Random Forest

In [42]:
print("-- Training the Model using Random Forest --")

model_rf = RandomForestClassifier(
    n_estimators = 100,   # 100 trees
    random_state = 42,
    n_jobs       = -1     # use all CPU cores for speed
)
model_rf.fit(train_X, train_y)

print(model_rf)
print("Done!")

-- Training the Model using Random Forest --
RandomForestClassifier(n_jobs=-1, random_state=42)
Done!

In [43]:
# Saving Trained Model
pickle.dump(model_rf, open('model_rf.pkl', 'wb'))
joblib.dump(model_rf, 'model_rf.joblib')
print("Model saved to model_rf.pkl and model_rf.joblib")

Model saved to model_rf.pkl and model_rf.joblib

In [44]:
# Load Saved Model
model_rf = pickle.load(open('model_rf.pkl', 'rb'))
print("Model loaded successfully!")

Model loaded successfully!

<div class="alert alert-block alert-success">
    <h1>6. Model Accuracy</h1>
</div>

In [45]:
model_rf_pred = model_rf.predict(test_X)
model_rf_pred

array([2, 2, 2, ..., 2, 2, 2], shape=(24000,))

In [46]:
model_rf_acc = accuracy_score(test_y, model_rf_pred)

print("-- Model Accuracy Score: ", end="")
print(round(model_rf_acc, 2) * 100)

-- Model Accuracy Score: 77.0

In [47]:
train_pred   = model_rf.predict(train_X)
train_acc    = accuracy_score(train_y, train_pred)

print(f"Train Accuracy : {round(train_acc, 4)*100:.2f}%")
print(f"Test  Accuracy : {round(model_rf_acc, 4)*100:.2f}%")

Train Accuracy : 100.00%
Test  Accuracy : 77.38%

<div class="alert alert-block alert-success">
    <h1>7. Application Phase</h1>
</div>

In [ ]:
import pandas as pd, numpy as np, pickle, joblib

# Load Model & Encoders
model    = pickle.load(open('model_rf.pkl', 'rb'))
encoders = joblib.load('encoders.pkl')


def encode_cols(le, value):
    if value in le.classes_:
        return le.transform([value])[0]
    else:
        return -1

print("Enter User Input:")

user_input = {
    "latitude"                    : float(input("Latitude (e.g. 37.77): ")),
    "longitude"                   : float(input("Longitude (e.g. -122.41): ")),
    "speed"                       : float(input("Speed km/h (e.g. 45.0): ")),
    "acceleration"                : float(input("Acceleration m/s2 (e.g. 1.5): ")),
    "steering_angle"              : int(input("Steering Angle -45 to 45 (e.g. 10): ")),
    "heading"                     : float(input("Heading 0-360 (e.g. 180.0): ")),
    "trip_duration"               : float(input("Trip Duration minutes (e.g. 30.0): ")),
    "trip_distance"               : float(input("Trip Distance km (e.g. 15.0): ")),
    "fuel_consumption"            : float(input("Fuel Consumption L/100km (e.g. 8.5): ")),
    "rpm"                         : float(input("RPM (e.g. 2500.0): ")),
    "brake_usage"                 : int(input("Brake Usage count 0-19 (e.g. 3): ")),
    "lane_deviation"              : float(input("Lane Deviation 0.0-1.0 (e.g. 0.2): ")),
    "weather_conditions"          : input("Weather (Sunny / Cloudy / Foggy / Rainy): "),
    "road_type"                   : input("Road Type (Urban / Highway / Rural): "),
    "traffic_condition"           : input("Traffic (Light / Moderate / Heavy): "),
    "stop_events"                 : int(input("Stop Events count (e.g. 2): ")),
    "route_deviation_score"       : float(input("Route Deviation Score 0.0-1.0 (e.g. 0.1): ")),
    "acceleration_variation"      : float(input("Acceleration Variation 0.0-1.0 (e.g. 0.2): ")),
    "behavioral_consistency_index": float(input("Behavioral Consistency Index 0.0-1.0 (e.g. 0.8): ")),
    "hour"                        : int(input("Hour 0-23 (e.g. 14): ")),
    "day_of_week"                 : int(input("Day of Week 0=Mon 6=Sun (e.g. 2): ")),
    "is_weekend"                  : int(input("Is Weekend 0=No 1=Yes: ")),
    "is_night"                    : int(input("Is Night 0=No 1=Yes: ")),
}

# Encode categorical string inputs
for col in ['weather_conditions','road_type','traffic_condition']:
    user_input[col] = encode_cols(encoders[col], user_input[col])


features = [
    'latitude','longitude','speed','acceleration','steering_angle',
    'heading','trip_duration','trip_distance','fuel_consumption','rpm',
    'brake_usage','lane_deviation','weather_conditions','road_type',
    'traffic_condition','stop_events','route_deviation_score',
    'acceleration_variation','behavioral_consistency_index',
    'hour','day_of_week','is_weekend','is_night'
]

X_input    = np.array([[user_input[col] for col in features]])
predict    = model.predict(X_input)
risk_label = encoders['risk_level'].inverse_transform(predict)[0]

print("\nPredicted Driving Risk Level:", risk_label)

advice = {
    'Low'   : 'Safe trip. Keep it up!',
    'Medium': 'Moderate risk. Drive carefully.',
    'High'  : 'HIGH RISK! Take immediate precautions.',
}
print("Advice:", advice.get(risk_label,""))

Enter User Input: