# <b>Lab 09 Task</b>
## Name: Muhammad jahanzaib
## RollNumber: SU92-BSAIM-S25-047

<div class="alert alert-block alert-warning">
    Dataset: <b>Driver Behavior &amp; Route Anomaly Dataset with Derived Features</b><br>
    120,000 records — Vehicle sensors, GPS, route &amp; behavioural signals
</div>

<div class="alert alert-block alert-danger">
    <b>Problem Statement</b><br>
    Predict the <b>Driving Risk Level</b> of a trip as <b>Low</b>, <b>Medium</b>, or <b>High</b>
    based on driver behaviour, vehicle sensor data, route anomalies and environmental conditions.
</div>

<div class="alert alert-block alert-info">
    <b>Machine Learning Steps</b><br>
    1. Data Reading / Data Loading<br>
    2. Data Exploration<br>
</div>

In [1]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: pandas in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

print("Librarie imported successfully!")

Librarie imported successfully!

<div class="alert alert-block alert-success">
    <h1>1. Data Reading / Data Loading</h1>
</div>

#### File: `driver_behavior_route_anomaly_dataset_with_derived_features.csv`

In [3]:
data = pd.read_csv('driver_behavior_route_anomaly_dataset_with_derived_features.csv')
print(f"Dataset loaded — {data.shape[0]:,} rows x {data.shape[1]} columns")
data

Dataset loaded — 16,749 rows x 26 columns

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.916143,-80.345269,39.484646,3.612832,6,212.555994,...,Sunny,Urban,Light,0,0,0,0,0.176974,0.715284,0.468189
1,2,105,2002,2023-01-01 00:00:01,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,...,Sunny,Highway,Light,0,0,1,0,0.229316,0.487761,0.234935
2,3,103,2002,2023-01-01 00:00:02,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,...,Cloudy,Urban,Moderate,0,0,0,0,0.473809,0.881141,0.192588
3,4,102,2002,2023-01-01 00:00:03,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,...,Sunny,Highway,Moderate,3,0,0,0,0.368063,0.937918,0.363707
4,5,101,2002,2023-01-01 00:00:04,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,...,Sunny,Rural,Moderate,0,0,0,0,0.145270,0.702187,0.178748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16744,16745,101,1001,2023-01-01 04:39:04,37.462194,-93.529184,2.227459,-0.443471,1,14.431451,...,Sunny,Urban,Moderate,0,0,0,0,0.354452,0.453228,0.314786
16745,16746,102,2002,2023-01-01 04:39:05,33.970967,-82.391802,55.214856,0.914161,-20,238.354196,...,Cloudy,Urban,Moderate,1,0,0,0,0.287305,0.394649,0.537739
16746,16747,104,4004,2023-01-01 04:39:06,46.021874,-84.632796,14.792704,0.024518,-17,290.431465,...,Foggy,Urban,Heavy,1,0,0,0,0.538708,0.783594,0.088477
16747,16748,101,1001,2023-01-01 04:39:07,42.456159,-92.703531,15.433994,0.393286,-16,53.519628,...,Sunny,Highway,Heavy,0,0,0,0,0.256577,0.801376,0.466376
16748,16749,103,5005,2023-01-01 04:39:08,34.852892,-111.847498,3.373280,-0.961855,-8,280.346454,...,Sunny,Urban,Moderate,0,0,0,0,0.257293,0.732797,0.338000

<div class="alert alert-block alert-success">
    <h1>2. Data Exploration</h1>
</div>

In [4]:
data.head()

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.916143,-80.345269,39.484646,3.612832,6,212.555994,...,Sunny,Urban,Light,0,0,0,0,0.176974,0.715284,0.468189
1,2,105,2002,2023-01-01 00:00:01,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,...,Sunny,Highway,Light,0,0,1,0,0.229316,0.487761,0.234935
2,3,103,2002,2023-01-01 00:00:02,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,...,Cloudy,Urban,Moderate,0,0,0,0,0.473809,0.881141,0.192588
3,4,102,2002,2023-01-01 00:00:03,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,...,Sunny,Highway,Moderate,3,0,0,0,0.368063,0.937918,0.363707
4,5,101,2002,2023-01-01 00:00:04,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,...,Sunny,Rural,Moderate,0,0,0,0,0.145270,0.702187,0.178748

In [5]:
data.tail()

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,...,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
16744,16745,101,1001,2023-01-01 04:39:04,37.462194,-93.529184,2.227459,-0.443471,1,14.431451,...,Sunny,Urban,Moderate,0,0,0,0,0.354452,0.453228,0.314786
16745,16746,102,2002,2023-01-01 04:39:05,33.970967,-82.391802,55.214856,0.914161,-20,238.354196,...,Cloudy,Urban,Moderate,1,0,0,0,0.287305,0.394649,0.537739
16746,16747,104,4004,2023-01-01 04:39:06,46.021874,-84.632796,14.792704,0.024518,-17,290.431465,...,Foggy,Urban,Heavy,1,0,0,0,0.538708,0.783594,0.088477
16747,16748,101,1001,2023-01-01 04:39:07,42.456159,-92.703531,15.433994,0.393286,-16,53.519628,...,Sunny,Highway,Heavy,0,0,0,0,0.256577,0.801376,0.466376
16748,16749,103,5005,2023-01-01 04:39:08,34.852892,-111.847498,3.373280,-0.961855,-8,280.346454,...,Sunny,Urban,Moderate,0,0,0,0,0.257293,0.732797,0.338000

In [6]:
data.shape

(16749, 26)

In [7]:
data.columns

Index(['trip_id', 'driver_id', 'vehicle_id', 'timestamp', 'latitude',
       'longitude', 'speed', 'acceleration', 'steering_angle', 'heading',
       'trip_duration', 'trip_distance', 'fuel_consumption', 'rpm',
       'brake_usage', 'lane_deviation', 'weather_conditions', 'road_type',
       'traffic_condition', 'stop_events', 'geofencing_violation',
       'anomalous_event', 'route_anomaly', 'route_deviation_score',
       'acceleration_variation', 'behavioral_consistency_index'],
      dtype='object')

In [8]:
data.count()

trip_id                         16749
driver_id                       16749
vehicle_id                      16749
timestamp                       16749
latitude                        16749
longitude                       16749
speed                           16749
acceleration                    16749
steering_angle                  16749
heading                         16749
trip_duration                   16749
trip_distance                   16749
fuel_consumption                16749
rpm                             16749
brake_usage                     16749
lane_deviation                  16749
weather_conditions              16749
road_type                       16749
traffic_condition               16749
stop_events                     16749
geofencing_violation            16749
anomalous_event                 16749
route_anomaly                   16749
route_deviation_score           16749
acceleration_variation          16749
behavioral_consistency_index    16749
dtype: int64

In [9]:
data.nunique()

trip_id                         16749
driver_id                           5
vehicle_id                          5
timestamp                       16749
latitude                        16749
longitude                       16749
speed                           16749
acceleration                    16749
steering_angle                     91
heading                         16749
trip_duration                   16749
trip_distance                   16749
fuel_consumption                16749
rpm                             16749
brake_usage                        18
lane_deviation                  16749
weather_conditions                  4
road_type                           3
traffic_condition                   3
stop_events                         8
geofencing_violation                2
anomalous_event                     2
route_anomaly                       2
route_deviation_score           16749
acceleration_variation          16749
behavioral_consistency_index    16749
dtype: int64

In [10]:
print('weather_conditions :', data['weather_conditions'].unique())
print('road_type          :', data['road_type'].unique())
print('traffic_condition  :', data['traffic_condition'].unique())

weather_conditions : ['Sunny' 'Cloudy' 'Foggy' 'Rainy']
road_type          : ['Urban' 'Highway' 'Rural']
traffic_condition  : ['Light' 'Moderate' 'Heavy']

In [11]:
data.describe()

,trip_id,driver_id,vehicle_id,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,...,rpm,brake_usage,lane_deviation,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
count,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,...,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000,16749.000000
mean,8375.000000,102.087169,2092.782674,39.984305,-90.017263,29.915739,1.023745,-0.043943,179.082382,3616.053555,...,1980.265730,4.998030,0.286318,0.994328,0.050928,0.098454,0.102454,0.284924,0.714267,0.286366
std,4835.164165,1.371403,1372.654585,5.018781,10.040329,29.805231,2.004559,14.773599,103.739636,3664.801035,...,1489.658872,2.233462,0.159778,0.999476,0.219858,0.297936,0.303253,0.158498,0.158353,0.159525
min,1.000000,101.000000,1001.000000,20.652155,-132.513636,0.002381,-0.999790,-45.000000,0.019805,0.310415,...,500.352694,0.000000,0.003648,0.000000,0.000000,0.000000,0.000000,0.003013,0.124308,0.001355
25%,4188.000000,101.000000,1001.000000,36.607808,-96.774774,8.709196,-0.416228,-10.000000,88.668384,1000.895499,...,932.265679,3.000000,0.162108,0.000000,0.000000,0.000000,0.000000,0.160108,0.611229,0.161755
50%,8375.000000,101.000000,1001.000000,40.027783,-90.066240,20.544647,0.401316,0.000000,179.526248,2478.794805,...,1525.058520,5.000000,0.265394,1.000000,0.000000,0.000000,0.000000,0.263970,0.734020,0.265834
75%,12562.000000,103.000000,3003.000000,43.381419,-83.221126,41.641406,1.840857,10.000000,267.716924,5019.397899,...,2547.298180,6.000000,0.390911,2.000000,0.000000,0.000000,0.000000,0.388654,0.837361,0.390835
max,16749.000000,105.000000,5005.000000,58.910939,-51.737448,307.209545,16.793666,45.000000,359.980254,40943.567214,...,15608.801077,19.000000,0.921417,7.000000,1.000000,1.000000,1.000000,0.885319,0.999540,0.942612

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16749 entries, 0 to 16748
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   trip_id                       16749 non-null  int64
 1   driver_id                     16749 non-null  int64
 2   vehicle_id                    16749 non-null  int64
 3   timestamp                     16749 non-null  object
 4   latitude                      16749 non-null  float64
 5   longitude                     16749 non-null  float64
 6   speed                         16749 non-null  float64
 7   acceleration                  16749 non-null  float64
 8   steering_angle                16749 non-null  int64
 9   heading                       16749 non-null  float64
 10  trip_duration                 16749 non-null  float64
 11  trip_distance                 16749 non-null  float64
 12  fuel_consumption              16749 non-null  float64
 13  rpm                           16749 non-null  float64
 14  brake_usage                   16749 non-null  int64
 15  lane_deviation                16749 non-null  float64
 16  weather_conditions            16749 non-null  object
 17  road_type                     16749 non-null  object
 18  traffic_condition             16749 non-null  object
 19  stop_events                   16749 non-null  int64
 20  geofencing_violation          16749 non-null  int64
 21  anomalous_event               16749 non-null  int64
 22  route_anomaly                 16749 non-null  int64
 23  route_deviation_score         16749 non-null  float64
 24  acceleration_variation        16749 non-null  float64
 25  behavioral_consistency_index  16749 non-null  float64
dtypes: float64(13), int64(9), object(4)
memory usage: 3.3+ MB

In [13]:
data.isnull().sum()

trip_id                         0
driver_id                       0
vehicle_id                      0
timestamp                       0
latitude                        0
longitude                       0
speed                           0
acceleration                    0
steering_angle                  0
heading                         0
trip_duration                   0
trip_distance                   0
fuel_consumption                0
rpm                             0
brake_usage                     0
lane_deviation                  0
weather_conditions              0
road_type                       0
traffic_condition               0
stop_events                     0
geofencing_violation            0
anomalous_event                 0
route_anomaly                   0
route_deviation_score           0
acceleration_variation          0
behavioral_consistency_index    0
dtype: int64